# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"remove_dsstore": "00_core.ipynb",
         "read_image": "01_image.ipynb",
         "resize_image": "01_image.ipynb",
         "AUTOTUNE": "02_dataloader.ipynb",
         "get_basename": "02_dataloader.ipynb",
         "show_batch": "02_dataloader.ipynb",
         "Clf": "02_dataloader.ipynb"}

modules = ["core.py",
           "image.py",
           "dataloader.py"]

doc_url = "https://aniketmaurya.github.io/chitra/"

git_url = "https://github.com/aniketmaurya/chitra/tree/master/"

def custom_doc_links(name): return None
