# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['read_image', 'resize_image']

# Cell
import tensorflow as tf
import numpy as np

from typing import Union

# Cell
def read_image(path: str, channels: int=3):
    """Reads an image file from the path and return the rgb image in . tf.Tensor format.
    """
    img: tf.Tensor = tf.io.read_file(path)
    img: tf.Tensor = tf.io.decode_image(img, channels=channels)
    return img

def resize_image(image: tf.Tensor, size: Union[tf.Tensor, tuple]):
     return tf.image.resize(image, size)