name: MkDocs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: make build-docs # copy README.md to docs/index.MD
      - run: pip install -r docs/requirements.txt
      - run: pip install .'[all]'
      - run: mkdocs gh-deploy --force
